@startuml

package "Media platform" {
    [Media playback] as MediaSource
    [DRM system] as PlatformDrm
}

package "App" {
    package "Libraries" {
        [DASH client] as Player
    }

    [Solution-specific logic and configuration] as AppLogic
}

Player -down-> PlatformDrm
Player -down-> MediaSource
Player -up-> AppLogic

@enduml