@startuml

[MPD]

[MPD] <-left- [MPEG DASH] : Defines

[MPD] --> [CMAF header] : Initialization segment
[MPD] --> [CMAF segment] : Media segment
[MPD] --> [ISOBMFF sidx] : Index segment

[MPEG CMAF] -up-> [CMAF header] : Defines
[MPEG CMAF] -up-> [CMAF segment] : Defines
[ISOBMFF] -up-> [ISOBMFF sidx] : Defines
[MPEG CMAF] -> [ISOBMFF] : Based on

@enduml