name: Build Pull Request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
        - 'build-tools/**'
        - 'data/boilerplate/**'
        - '.github/workflows/build-container.yml'


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dash-industry-forum/dashif-specs:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      env:
        # Reset OPTS to empty to make sure we are not using
        # interactive mode in CI
        OPTS:
      run: make -f /tools/Makefile
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
