name: Publish Bikeshed Document

on:
  push:
    branches:
      - bikeshed-builds

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: ./setup.sh
    - name: Build
      env:
        # Reset OPTS to empty to make sure we are not using
        # interactive mode in CI
        OPTS:
      run: ./build.sh
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4
