name: Publish Bikeshed Document

on:
  push:
    branches:
      - bikeshed-builds

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dash-industry-forum/dashif-specs:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      env:
        # Reset OPTS to empty to make sure we are not using
        # interactive mode in CI
        OPTS:
      run: make -f /tools/Makefile
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: package
    steps:
        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4
